_wandb:
    value:
        cli_version: 0.22.3
        e:
            0wrm06tn850hiyyclr2x2sjcx53je0ot:
                args:
                    - --model_name_or_path
                    - Qwen/Qwen3-VL-8B-Instruct
                    - --learning_rate
                    - "5e-6"
                    - --max_grad_norm
                    - "0.1"
                    - --per_device_train_batch_size
                    - "1"
                    - --gradient_checkpointing
                    - --gradient_accumulation_steps
                    - "2"
                    - --output_dir
                    - /home/jn20658/ziwen/OPSD_dc/checkpoints
                    - --run_config
                    - qwen38b_vl_gen1024_fixteacher_temp11_forwardbeta0_clip006
                    - --num_train_epochs
                    - "1"
                    - --max_completion_length
                    - "1024"
                    - --save_steps
                    - "25"
                    - --logging_steps
                    - "2"
                    - --attn_implementation
                    - flash_attention_2
                    - --torch_dtype
                    - bfloat16
                    - --max_length
                    - "10000"
                    - --beta
                    - "0"
                    - --use_vllm
                    - --vllm_mode
                    - colocate
                    - --vllm_gpu_memory_utilization
                    - "0.4"
                    - --vllm_tensor_parallel_size
                    - "2"
                    - --use_peft
                    - --lora_r
                    - "64"
                    - --lora_alpha
                    - "128"
                    - --lora_target_modules
                    - q_proj
                    - k_proj
                    - v_proj
                    - o_proj
                    - gate_proj
                    - up_proj
                    - down_proj
                    - --temperature
                    - "1.1"
                    - --top_p
                    - "0.95"
                    - --top_k
                    - "20"
                    - --lmbda
                    - "1"
                    - --fixed_teacher
                    - "False"
                    - --jsd_token_clip
                    - "0.06"
                    - --wandb_project
                    - OPSD
                codePath: opsd_train.py
                codePathLocal: opsd_train.py
                cpu_count: 192
                cpu_count_logical: 384
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "89930072064"
                        used: "69944631296"
                email: lic049@ucsd.edu
                executable: /scratch/fs201130/jn20658/miniconda3/envs/opsd/bin/python
                git:
                    commit: 7448751f307a9cdbcc1246dd1565a1a605b443df
                    remote: https://github.com/ZackZeng999/OPSD_dc.git
                gpu: NVIDIA H100
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100
                      uuid: GPU-db8f09ee-3f91-ecc1-e49e-82c11d62515c
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100
                      uuid: GPU-91bf0f2f-f019-2bcf-66ec-98717c5d2dd7
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100
                      uuid: GPU-78812146-c982-8787-cca7-b873e7b869da
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100
                      uuid: GPU-6dbd6c93-b41e-7bda-0be2-7e739927077e
                host: n3021-022
                memory:
                    total: "811150839808"
                os: Linux-5.14.0-570.58.1.el9_6.x86_64-x86_64-AMD_EPYC_9654_96-Core_Processor-with-glibc2.34
                program: /home/jn20658/ziwen/OPSD_dc/opsd_train.py
                python: CPython 3.10.20
                root: /home/jn20658/ziwen/OPSD_dc
                slurm:
                    cluster_name: lnz-musica
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000001
                    cpu_bind_list: 0x000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000001
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "352"
                    distribution: cyclic
                    gpus_on_node: "4"
                    gtids: "0"
                    install_prefix: /opt/slurm/rocky-9.6/25-11-3-1
                    job_account: p201130
                    job_cpus_per_node: "176"
                    job_end_time: "1810649904"
                    job_gid: "100466"
                    job_group: jn20658
                    job_id: "50154"
                    job_name: bash
                    job_nodelist: n3021-022
                    job_num_nodes: "1"
                    job_partition: zen4_0768_h100x4
                    job_qos: zen4_0768_h100x4
                    job_start_time: "1779113904"
                    job_uid: "100466"
                    job_user: jn20658
                    jobid: "50154"
                    launch_node_ipaddr: 10.87.0.11
                    localid: "0"
                    mem_per_node: "763000"
                    mpi_type: pmix
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: n3021-022
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    pmix_mapping_serv: (vector,(0,1,1))
                    pmixp_abort_agent_port: "45917"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "44921"
                    pty_win_col: "90"
                    pty_win_row: "20"
                    srun_comm_host: 10.87.0.11
                    srun_comm_port: "42753"
                    step_gpus: 0,1,2,3
                    step_id: "0"
                    step_launcher_port: "42753"
                    step_nodelist: n3021-022
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /home/jn20658/ziwen
                    submit_host: login01
                    task_pid: "1212041"
                    tasks_per_node: "1"
                    topology_addr: n3021-022
                    topology_addr_pattern: node
                    tres_per_task: cpu=22,gres/gpu=1
                    umask: "0022"
                startedAt: "2026-05-18T15:04:57.253544Z"
                writerId: 0wrm06tn850hiyyclr2x2sjcx53je0ot
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 84
                - 95
                - 98
            "2":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 51
                - 71
                - 84
                - 95
                - 98
            "3":
                - 13
                - 16
            "4": 3.10.20
            "5": 0.22.3
            "6": 4.57.1
            "12": 0.22.3
            "13": linux-x86_64
beta:
    value: 0
effective_batch_size:
    value: 8
ema_decay:
    value: null
fixed_teacher:
    value: false
gradient_accumulation_steps:
    value: 2
gradient_checkpointing:
    value: true
learning_rate:
    value: 5e-06
lmbda:
    value: 1
lora_alpha:
    value: 128
lora_r:
    value: 64
max_completion_length:
    value: 1024
max_length:
    value: 10000
model_name:
    value: Qwen/Qwen3-VL-8B-Instruct
num_processes:
    value: 4
num_train_epochs:
    value: 1
per_device_train_batch_size:
    value: 1
temperature:
    value: 1.1
top_k_loss:
    value: null
use_ema_teacher:
    value: false
use_peft:
    value: true
use_tinker_loss:
    value: false
