accelerate launch \
    --config_file accelerate.yaml \
    --num_processes 4 \
    --gpu_ids 0,1,2,3 \
    --gradient_accumulation_steps 2 \
    --main_process_port 12949 \
    opsd_train.py \
    --model_name_or_path Qwen/Qwen3-VL-8B-Instruct \
    --learning_rate 5e-6 \
    --max_grad_norm 0.1 \
    --per_device_train_batch_size 1 \
    --gradient_checkpointing \
    --gradient_accumulation_steps 2 \
    --output_dir /scratch/fs201130/jn20658/opsd_checkpoints \
    --run_config qwen38b_vl_gen1024_fixteacher_temp11_forwardbeta0_clip006 \
    --num_train_epochs 1 \
    --max_completion_length 1024 \
    --save_steps 25 \
    --save_total_limit 1 \
    --logging_steps 2 \
    --attn_implementation flash_attention_2 \
    --torch_dtype bfloat16 \
    --max_length 10000 \
    --beta 0 \
    --use_vllm \
    --vllm_mode colocate \
    --vllm_gpu_memory_utilization 0.4 \
    --vllm_tensor_parallel_size 2 \
    --use_peft \
    --lora_r 64 \
    --lora_alpha 128 \
    --lora_target_modules q_proj k_proj v_proj o_proj gate_proj up_proj down_proj \
    --temperature 1.1 \
    --top_p 0.95 \
    --top_k 20 \
    --lmbda 1 \
    --fixed_teacher False\
    --jsd_token_clip 0.06 \
    --wandb_project OPSD
